Simplify Jenkins pipelines to only check VALJEAN_SPACK_ROOT once

diff --git a/ci/Jenkinsfile b/ci/Jenkinsfile
--- a/ci/Jenkinsfile
+++ b/ci/Jenkinsfile
@@ -49,14 +49,16 @@ pipeline {
         }
         echo "Starting build ${env.BUILD_ID} on ${env.JENKINS_URL}..."
         sh """#!/bin/bash
-        if [ "x${env.VALJEAN_SPACK_ROOT}" != x ]; then
-          source "${SRC}/ci/spack-python.sh" "${env.VALJEAN_SPACK_ROOT}"
-        fi
-        python3 -m venv "${TOX_VENV}"
-        source "${TOX_VENV}/bin/activate"
-        python3 -m pip install --upgrade pip setuptools wheel
-        python3 -m pip install tox poetry
-        """
+           if [ "x${env.VALJEAN_SPACK_ROOT}" == x ]; then
+             echo "The VALJEAN_SPACK_ROOT environment variable is undefined. The pipeline fails here."
+             exit 1
+           fi
+           source "${SRC}/ci/spack-python.sh" "${env.VALJEAN_SPACK_ROOT}"
+           python3 -m venv "${TOX_VENV}"
+           source "${TOX_VENV}/bin/activate"
+           python3 -m pip install --upgrade pip setuptools wheel
+           python3 -m pip install tox poetry
+           """
       }
     }
     stage('Build and check HTML doc') {
@@ -64,12 +66,10 @@ pipeline {
         echo 'Building and checking documentation...'
         dir("${SRC}") {
           catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
-            sh """
-                if [ "x${env.VALJEAN_SPACK_ROOT}" != x ]; then
-                  source "${SRC}/ci/spack-python.sh" "${env.VALJEAN_SPACK_ROOT}"
-                fi
-                source "${TOX_VENV}/bin/activate"
-                ${TOX} -e docs
+            sh """#!/bin/bash
+               source "${SRC}/ci/spack-python.sh" "${env.VALJEAN_SPACK_ROOT}"
+               source "${TOX_VENV}/bin/activate"
+               ${TOX} -e docs
                 """
           }
         }
@@ -80,13 +80,11 @@ pipeline {
         echo 'Linting...'
         dir("${SRC}") {
           catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
-            sh """
-                if [ "x${env.VALJEAN_SPACK_ROOT}" != x ]; then
-                  source "${SRC}/ci/spack-python.sh" "${env.VALJEAN_SPACK_ROOT}"
-                fi
-                source "${TOX_VENV}/bin/activate"
-                ${TOX} -e linting valjean/ tests/ | tee "${REPORTS}/linting.out"
-                """
+            sh """#!/bin/bash
+               source "${SRC}/ci/spack-python.sh" "${env.VALJEAN_SPACK_ROOT}"
+               source "${TOX_VENV}/bin/activate"
+               ${TOX} -e linting valjean/ tests/ | tee "${REPORTS}/linting.out"
+               """
           }
         }
       }
@@ -96,12 +94,10 @@ pipeline {
         echo 'Running unit tests...'
         dir("${SRC}") {
           sh """#!/bin/bash
-              if [ "x${env.VALJEAN_SPACK_ROOT}" != x ]; then
-                source "${SRC}/ci/spack-python.sh" "${env.VALJEAN_SPACK_ROOT}"
-              fi
-              source "${TOX_VENV}/bin/activate"
-              TOX_PARALLEL_NO_SPINNER=1 ${TOX} --parallel 4 -- valjean/ tests/ | tee "${REPORTS}/testing.out"
-              """
+             source "${SRC}/ci/spack-python.sh" "${env.VALJEAN_SPACK_ROOT}"
+             source "${TOX_VENV}/bin/activate"
+             TOX_PARALLEL_NO_SPINNER=1 ${TOX} --parallel 4 -- valjean/ tests/ | tee "${REPORTS}/testing.out"
+             """
         }
       }
     }
diff --git a/ci/Jenkinsfile.nightly b/ci/Jenkinsfile.nightly
--- a/ci/Jenkinsfile.nightly
+++ b/ci/Jenkinsfile.nightly
@@ -32,9 +32,11 @@ pipeline {
         withFolderProperties {
           echo "Starting build ${env.BUILD_ID} on ${env.JENKINS_URL}..."
           sh """#!/bin/bash
-          if [ "x${env.VALJEAN_SPACK_ROOT}" != x ]; then
-            source "${SRC}/ci/spack-python.sh" "${env.VALJEAN_SPACK_ROOT}"
+          if [ "x${env.VALJEAN_SPACK_ROOT}" == x ]; then
+            echo "The VALJEAN_SPACK_ROOT environment variable is undefined. The pipeline fails here."
+            exit 1
           fi
+          source "${SRC}/ci/spack-python.sh" "${env.VALJEAN_SPACK_ROOT}"
           python3 -m venv "${TOX_VENV}"
           source "${TOX_VENV}/bin/activate"
           python3 -m pip install --upgrade pip setuptools wheel
@@ -51,16 +53,14 @@ pipeline {
             catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
               withFolderProperties {
                 sh """#!/bin/bash
-                    if [ "x${env.VALJEAN_SPACK_ROOT}" != x ]; then
-                      source "${SRC}/ci/spack-python.sh" "${env.VALJEAN_SPACK_ROOT}"
-                    fi
-                    source "${TOX_VENV}/bin/activate"
-                    for script in "${NIGHTLIES}"/scripts/valjean_nightly*.py; do
-                      script_base=\$(basename \${script})
-                      echo "Running tests for \${script_base}"
-                      ${TOX} -e parsing -- --parsing-config-file-t4="\${script}" --junit-prefix="\${script_base}" --junit-xml="${REPORTS}/pytest-\${script_base}.xml" --cov-report=xml:"${REPORTS}/coverage-\${script_base}.xml" | tee "${REPORTS}/testing-\${script_base}.out"
-                    done
-                    """
+                   source "${SRC}/ci/spack-python.sh" "${env.VALJEAN_SPACK_ROOT}"
+                   source "${TOX_VENV}/bin/activate"
+                   for script in "${NIGHTLIES}"/scripts/valjean_nightly*.py; do
+                     script_base=\$(basename \${script})
+                     echo "Running tests for \${script_base}"
+                     ${TOX} -e parsing -- --parsing-config-file-t4="\${script}" --junit-prefix="\${script_base}" --junit-xml="${REPORTS}/pytest-\${script_base}.xml" --cov-report=xml:"${REPORTS}/coverage-\${script_base}.xml" | tee "${REPORTS}/testing-\${script_base}.out"
+                   done
+                   """
               }
             }
           }
